### ! Показать все карточки
GET http://localhost:3000/cards
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### ! Создать карточку
POST http://localhost:3000/cards
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "name1112qa",
  "link": "link"
}


### ! Удалить карточку
DELETE http://localhost:3000/cards/6374c31154d35d5ffa46836d
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### ! Поставить лайк карточке
PUT http://localhost:3000/cards/636fdd59120f6313ebc0ed72/likes
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### ! Удалить лайк с карточки
DELETE http://localhost:3000/cards/636fdd59120f6313ebc0ed72/likes
Accept: */*
Cache-Control: no-cache
Content-Type: application/json