GET http://localhost:3000/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: 12qweqweqw

###
POST http://localhost:3000/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "test",
  "about": "about",
  "avatar": "https://ya.ru/av.bmp"
}

###
GET http://localhost:3000/users/text
Accept: */*
Cache-Control: no-cache
Content-Type: application/json