### Создать пользователя
POST http://localhost:3000/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "Тестовый пользователь2",
  "about": "Инфо о себе",
  "avatar": "https://sobakovod.club/uploads/posts/2021-12/thumbs/1639670110_37-sobakovod-club-p-sobaki-sobachku-malenkuyu-na-telefon-37.jpg"
}

### Показать всех пользователей
GET http://localhost:3000/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### Поиск пользователя по ID
GET http://localhost:3000/users/636fa80e7081e161d24a6a4c
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### Показать все карточки
GET http://localhost:3000/cards
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### Добавить карточку
POST http://localhost:3000/cards
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "себек2",
  "link": "https://sobakovod.club/uploads/posts/2021-12/thumbs/1639670110_37-sobakovod-club-p-sobaki-sobachku-malenkuyu-na-telefon-37.jpg"
}

### Удалить карточку
DELETE http://localhost:3000/cards/6370d1bc249a47c854849b1d
Accept: */*
Cache-Control: no-cache
Content-Type: application/json